#!/bin/bash
# -------------------------------------------------------
# Log Shipping Setup — Requests v1.0
# CURA Medical Specialists Imaging Request System
#
# Configures:
#   1. rsyslog forwarding to remote syslog server
#   2. Log rotation for /var/log/requests/*.log
#
# INFRA-007, GOLV-013: Off-box log shipping (tamper-resistant)
#
# Usage:
#   sudo bash deploy/setup-logshipping.sh
# -------------------------------------------------------

set -euo pipefail

# -------------------------------------------------------
# Configuration
# -------------------------------------------------------
# CUSTOMIZE: Remote syslog server (TCP for reliability)
REMOTE_SYSLOG_HOST="${REMOTE_SYSLOG_HOST:-syslog.curaspecialists.com.au}"
REMOTE_SYSLOG_PORT="${REMOTE_SYSLOG_PORT:-514}"
REMOTE_SYSLOG_PROTOCOL="${REMOTE_SYSLOG_PROTOCOL:-tcp}"  # tcp or udp

LOGROTATE_CONF="/etc/logrotate.d/requests"
RSYSLOG_CONF="/etc/rsyslog.d/50-requests.conf"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== Requests v1.0 — Log Shipping Setup ==="
echo ""

# -------------------------------------------------------
# Step 1: Ensure rsyslog is installed
# -------------------------------------------------------
echo "[1/4] Checking rsyslog installation..."
if ! command -v rsyslogd &>/dev/null; then
    echo "Installing rsyslog..."
    apt-get update -qq && apt-get install -y rsyslog
else
    echo "rsyslog is already installed."
fi

# -------------------------------------------------------
# Step 2: Configure rsyslog forwarding
# -------------------------------------------------------
echo "[2/4] Configuring rsyslog forwarding to ${REMOTE_SYSLOG_HOST}:${REMOTE_SYSLOG_PORT}..."

# Determine protocol prefix
PROTO_PREFIX="@@"  # TCP by default
if [[ "${REMOTE_SYSLOG_PROTOCOL}" == "udp" ]]; then
    PROTO_PREFIX="@"
fi

cat > "${RSYSLOG_CONF}" <<RSYSLOG_EOF
# -------------------------------------------------------
# Requests v1.0 — Remote syslog forwarding
# Auto-generated by setup-logshipping.sh
# -------------------------------------------------------

# Load imfile module to monitor application log files
module(load="imfile" PollingInterval="10")

# Monitor health-monitor log
input(type="imfile"
    File="/var/log/requests/health-monitor.log"
    Tag="requests-health"
    Severity="info"
    Facility="local0")

# Monitor backup log
input(type="imfile"
    File="/var/log/requests/backup.log"
    Tag="requests-backup"
    Severity="info"
    Facility="local0")

# Monitor retention log
input(type="imfile"
    File="/var/log/requests/retention.log"
    Tag="requests-retention"
    Severity="info"
    Facility="local0")

# Monitor alert log
input(type="imfile"
    File="/var/log/requests/alerts.log"
    Tag="requests-alert"
    Severity="warning"
    Facility="local0")

# Forward all requests logs to remote syslog server
local0.* ${PROTO_PREFIX}${REMOTE_SYSLOG_HOST}:${REMOTE_SYSLOG_PORT}
RSYSLOG_EOF

echo "rsyslog config written to ${RSYSLOG_CONF}"

# -------------------------------------------------------
# Step 3: Install logrotate configuration
# -------------------------------------------------------
echo "[3/4] Installing logrotate configuration..."

cp "${SCRIPT_DIR}/logrotate-requests.conf" "${LOGROTATE_CONF}"
echo "logrotate config installed to ${LOGROTATE_CONF}"

# -------------------------------------------------------
# Step 4: Restart rsyslog
# -------------------------------------------------------
echo "[4/4] Restarting rsyslog..."
systemctl restart rsyslog
systemctl enable rsyslog

echo ""
echo "=== Log shipping setup complete ==="
echo ""
echo "IMPORTANT: Update REMOTE_SYSLOG_HOST in ${RSYSLOG_CONF}"
echo "           if not using the default: ${REMOTE_SYSLOG_HOST}:${REMOTE_SYSLOG_PORT}"
echo ""
echo "Verify with: logger -p local0.info 'Test from Requests v1.0' && tail -f /var/log/syslog"
